newdeal:
  api:
    backend_url: ${NEWDEAL_API_BACKEND_URL}
    front_url: ${NEWDEAL_API_FRONT_URL}
    security_url: ${NEWDEAL_API_SECURITY_URL}
    backend_protocol: ${NEWDEAL_API_BACKEND_PROTOCOL}
    front_protocol: ${NEWDEAL_API_FRONT_PROTOCOL}
    security_protocol: ${NEWDEAL_API_SECURITY_PROTOCOL}

logging:
  pattern:
    console: '[NewDeal-Frond] %d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5p){faint}
              %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){faint} %clr(%-40.40logger{0}){faint}
              %clr(:){faint} %clr(%m){faint}%n'
  file: ./logs/infraFront.log
  file.max-history: 5
  level:
    com:
      broadwave:
        front: DEBUG
    org:
      hibernate: INFO
    root: INFO

server:
  port: 8010
  servlet:
    session:
      timeout: 480m

spring:
  output:
    ansi:
      enabled: ALWAYS
  devtools: 
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
