newdeal:
  api:
    backend_url: 192.168.0.144
    front_url: 192.168.0.144
    security_url: 192.168.0.144

logging:
  file: ./logs/infraFront.log
  file.max-history: 5
  level:
    kr:
      co:
        broadwave: DEBUG
    org:
      hibernate: INFO
    root: INFO

server:
  port: 8010
  servlet:
    session:
      timeout: 480m

spring:
  output:
    ansi:
      enabled: ALWAYS
  devtools: 
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
    